### ISSUE TITLE
Wifi Compatibility?

### ISSUE THREAD

**Issue by ME1234568** [balopez83/Surface_Pro_3_Hackintosh#1]
Hi,

I was attempting to install this but ran into a little bit of a hiccup with the Wi-Fi. The wording is a bit confusing with whether or not I can use the built-in wifi (it says its not compatible, but using the internal wifi is refrenced several times and there's a kext named Avastar). I do have a usb dongle, but it appears that I can't install it until after MacOS is installed, but I can't install MacOS without wifi. I'm trying to install catalina, if it's possible to use it on a different version I would like to know.

**Comment by balopez83** [comment]
Hi @ME1234568 sorry for the confusion. The built in WiFi and Bluetooth is not supported by macOS. The Avastar kext was a kext used with the Surface Pro 1 & 2 to get Bluetooth working and I will be attempting to get bluetooth working on the Pro 3 as well though it likely won't end up working. 

Catalina, Big Sur, and Monterey, should all be able to be installed by simply selecting the option when asked that says something along the lines of "your computer does not have an ethernet or WiFi card installed". You can sign into iCloud stuff after you have been able to get to the desktop and install your USB WiFi card.

**Comment by ME1234568** [comment]
Hi @balopez83,

Thanks for your reply. I do have a netgear dongle that should work. Are the kexts for those already installed or would I have to do that manually?

**Comment by balopez83** [comment]
You would need to install it manually after. While the kexts should already be included in the EFI you still need the wifi client installed in macOS to actually turn on and manage the wifi adapter. 
If your adapter is designed for macOS it likely will work with this software maintained here: https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter

If that doesn't work you would need to rely on your netgear software if its compatible.
