### ISSUE TITLE
5.2 Graphical Issues Continues

### ISSUE THREAD

**Issue by theholyjosh1** [balopez83/Surface_Pro_3_Hackintosh#13]

**Comment by theholyjosh1** [comment]
oops, forgot to add descriptions but, when I updated to 5.2 on my i7 model, the graphic issues continued again. because I had so much apps on startup that use a lot of graphics it was extremely glitchy, luckily I could downgrade my EFI to 5.1 again and everything is fine. As you said on issue #9 to re-open the issue, I am unsure how to do that so I just said ill open a new issue if that's alright.

**Comment by balopez83** [comment]
@ShibeGG1 I added a new minor release 5.2.1 which has config.plist files containing the fixes from release 5.2.0 but with the desktop graphics profile that works with your particular machine from version 5.1.0. 

Please download release 5.2.0 or use your existing download if you still have it and replace your existing config.plist with the one in 5.2.1. Copy over your SMBIOS information if you have set that up and then copy back to your EFI partition. You should then be able to boot with the latest fixes and have graphics stable. 

Not sure why 5.2.0 isn't working for your i7 machine but is for other i7 machines, but I will keep looking into it and hopefully fix it in a later release.
