### ISSUE TITLE
power management

### ISSUE THREAD

**Issue by Nyryzu** [balopez83/Surface_Pro_3_Hackintosh#14]
Hey @balopez83, my computer is actually back to running very hot, not much activity going on, just simple browsing thats it.

The fans turn up all of a sudden and when I feel the back of the surface it is very hot. Coconut battery just shows me a constant battery temp although I can see that battery usage gets  all the way to around 15W (I think its ridiculously high for casual use)  
So if there is any other way to further diagnose this issue please let me know.

Thank you so much

**Comment by balopez83** [comment]
Hi @Nyryzu I think this is an unexpected issue with the fact that we have to use an SMBIOS that is a few generations newer than the proper one for this machine. This is required to allow use of the latest macOS versions but I believe its causing improper power management of the CPU. Basically the CPU is not being allowed to slow down despite there not being any actual work for it to do. 

I am testing CPUfriend.kext and a custom satellite to see if the CPU will reduce power consumption and as a result reduce the fan speed. So far it is looking promising and I hope to release an updated release soon. If you would like to add the following two kexts to your EFI and add them to your config.plist and report back to let me know if it resolves your issue I would appreciate it. 
[CPUFriend.kext.zip](https://github.com/balopez83/Surface_Pro_3_Hackintosh/files/11846817/CPUFriend.kext.zip)
[CPUFriendDataProvider.kext.zip](https://github.com/balopez83/Surface_Pro_3_Hackintosh/files/11846818/CPUFriendDataProvider.kext.zip)

Edit: I do think it is somewhat normal for the fans to spin up when plugged in and actively charging but they should calm down soon after reaching 100% or when on battery power.

**Comment by balopez83** [comment]
@Nyryzu I have been testing CPUFriend and CPUFriendDataProvider and it seems to be working quite well for me. My surface is all but completely silent except when doing high demand activities or when charging which is expected. 

I will be integrating these changes into the next release. Keep in mind the next release will be a structural/functional change due to a battery issue discovered impacting users that dual boot with non macOS OS's due to the Surface Pro 3's broken ACPI code.

**Comment by balopez83** [comment]
I reverted to a more appropriate SMBIOS that appears to have resolved the high CPU usage as well as a number of other issues. CPUFriend won't be supported with that particular SMBIOS and so I am not including that since it should no longer be needed. See release 6.0.0 for this fix.
