### ISSUE TITLE
Infinite loading into installation

### ISSUE THREAD

**Issue by dima2903studio** [balopez83/Surface_Pro_3_Hackintosh#18]
I have made a bootable USB drive, copied EFI, booted the device. It loaded into it's bootloader, I selected 2nd option "MacOS Base System", and then progress bar appears under the Apple logo. After it disappears, a desktop with gray background appears, and nothing happens. What should I do to make it load?

**Comment by balopez83** [comment]
Hi @dima2903studio it sounds like you have a defective installer. You should not have an option for "MacOS Base System" and instead it should say something like "macOS Monterey Installer" or something similar. It sounds like you might have created a mac recovery image which will only work on a mac or a hackintosh that has a built in compatible wifi card which the Surface Pro 3 does not have. 

How did you make your install USB?

**Comment by Xryphon** [comment]
**Edit:** Do not follow the advice in the original comment below. It is wrong. 

You are required to use the online installer to get macOS. Windows is not able to interact with the HFS/ Apple partitions so it cannot create an offline installer in any way. The only way to get macOS installed on your Surface is to use HoRNDIS, which is included within the kexts of the EFI. Not sure why it is not mentioned within the instructions, but... here we are.

HoRNDIS allows you to use USB tethering on your phone to give your device a Wi - Fi signal. The Wi - Fi symbol will not show up, but the connection is there once you plug your device in. Install macOS like you normally would - 10.15 (Catalina) has given me the least errors compared to the other versions in the past. Make sure you transfer your EFI file to your actual SSD after installation. 

To the owner: I highly recommend updating the guide for installation. The webpage that is linked in step #1 is over three years old and dates back to the Clover days. 

**Original:** (Please ignore)

Heyo,

If you use the tutorial provided it tells you to use the command `python gibMacOS.command -r -v <macos version>`

However, you just want to run the batch script `gibMacOS.bat` and choose one from there to get your full recovery file. If you run the command you get the security update instead, which is not what you want.

**Comment by balopez83** [comment]
@dima2903studio Marking this item closed as the instructions above should resolve the issue. 

If that does not work there are instructions online for making a VMWare macOS virtual machine which works very well for making a boot disk. Alternatively, if you have access to a real mac that you can borrow, that also would work to create a boot disk.

@Xryphon updated links to reflect the latest drivers. while that software would still work, the latest is definitely better.
