### ISSUE TITLE
Setup crashing after selecting region

### ISSUE THREAD

**Issue by theholyjosh1** [balopez83/Surface_Pro_3_Hackintosh#19]
After installing Ventura, when I get to the setup, the first part is selecting country and region. I select my country, and click continue. It freezes for about 2 seconds then the screen goes gray. A few seconds after, a popular appears saying setup assistant has quit unexpectedly. After about 15 seconds after the pop up appears without selecting anything it shuts off and restarts, with the same thing happening in a loop. Clicking reopen just reopens setup and it crashes again.
Thanks.

**Comment by balopez83** [comment]
@ShibeGG1 this is expected. The SP3 does not have native graphics support. It is recommended to download all the required stuff outlined in on the readme and elsewhere (ie OpenCore Legacy Patcher) while on a Monterey install and upgrade to Ventura. The setup screen on Ventura is notoriously glitchy without graphics acceleration and can take a significant number of attempts before successfully finishing if done as a clean install.

**Comment by ShibeGG1** [comment]
ah i see now. that makes sense. thank you very much!

**Comment by theholyjosh1** [comment]
ah i see now. that makes sense. thank you very much!

**Comment by balopez83** [comment]
@ShibeGG1 In case you run into this issue again I have enabled Apple Hotkey support and so at the OpenCore boot selection you can press "Shift+Enter" on macOS to enter Safe Mode. While it will be painfully slow to get through the first boot setup it should not crash.
