### ISSUE TITLE
MacOS Sonoma (Not Bug)

### ISSUE THREAD

**Issue by theholyjosh1** [balopez83/Surface_Pro_3_Hackintosh#20]
OCLP 1.0.0 came out with the support of Sonoma. Can we install sonoma right now? do you recommend it?

**Comment by balopez83** [comment]
Hi @ShibeGG1 currently Sonoma isn't yet supported in my EFI. I have tested it though it is a bit slow. While you could change the SMBIOS to a compatible one to upgrade I would recommend holding off. The next EFI release I issue will have some kext upgrades that I have to manually patch and so while it will take time, I believe it will support Sonoma much better.

I do intend to support macOS on the SP3 until OCLP or Apple drops support. I suspect Sonona will be the last OS release to support x64 based processors but who knows.

I don't have an ETA on the next release but hopefully soon.

**Comment by balopez83** [comment]
Hi @ShibeGG1 I just posted a new release 7.0.1 that has several fixes, updates, and SMBIOS change. You can now install macOS Sonoma and while it might be a little slow it should work fairly reliably.
