### ISSUE TITLE
VSC Glitch

### ISSUE THREAD

**Issue by fjosue4** [balopez83/Surface_Pro_3_Hackintosh#21]
Hello,  I'm having glitches with VSC using the [6.1.1](https://github.com/balopez83/Surface_Pro_3_Hackintosh/releases/tag/6.1.1) EFI version, couldn't install the latest version. I already disabled GPU acceleration in the program settings, do you have an idea on how to fix it?

This happens only on Visual Studio Code (By now) Other programs such as Chrome fixed disabling GPU acceleration.

https://github.com/balopez83/Surface_Pro_3_Hackintosh/assets/85136931/fa5de06c-47e0-4522-be52-1b498e8570c1

Thanks!

**Comment by balopez83** [comment]
@fjosue4 Yes graphics glitches are common with macOS and this graphics chipset unfortunately.

Make sure you're using the correct plist for your machine in that version. Normally I would say that you really should upgrade to the latest version since I have made improvements to graphics in the latest versions. I have actually discovered new fixes for several items and my next release 8.0.0 will change the SMBIOS again for a final time but among other fixes should further resolve those graphics glitches.

I can't give an ETA on that release as I am still fine tuning my SP4 repo at which point I can bring those fixes down to the SP3. 

Not sure how much it will help without other very much needed fixes but you can try adding the key AAPL,GfxTile with the DATA Value of 01000000 to your graphics device in your config.plist

Hope that helps improve the glitches. If not, know that I do have some fixes coming that should greatly improve or even resolve those glitches.

**Comment by fjosue4** [comment]
Thanks for the quick reply @balopez83 

I'll try reinstalling with the value 01000000 as you mentioned.

About using v7.0.2, I get the error 
`[ext4] Error Mounting: Out of resources 
Halting on critical error`

Any clue? I use the non-i7 config.plist since I got the i5 version but even with the i7 plist I cannot install using your last version, should I modify something else on the config.plist

**Comment by balopez83** [comment]
Looks like you have an ext4 partition either on an SSD card or on your SSD. I believe I forgot to include the correct ext4 driver in that release. You can either move the correct ext4-dxe driver from an older release and activate it instead of the ext4 driver that is in there. If you don't care about booting Linux or chrome you can simply disable the driver. 

I don't have that release in front of me to confirm the exact driver names but for whatever reason the default ext4 driver included with the OpenCore releases does not work.

**Comment by fjosue4** [comment]
Got it, I'll try to look for it tomorrow if the AAPL,GfxTile doesn't fix it :D thanks @balopez83 !

**Comment by fjosue4** [comment]
Update: 
I was able to install using the old version `Ext4Dxe.efi` in the new one as you said @balopez83 .
Sadly the VSC is worst on this new version, the program is not rendering fonts or icons.

The good part is it's a different problem haha 

![Captura de Pantalla 2023-11-18 a la(s) 06 48 37](https://github.com/balopez83/Surface_Pro_3_Hackintosh/assets/85136931/77378695-1351-487b-895f-305232a8654f)

If I find some other fix I'll update here.

**Comment by balopez83** [comment]
@fjosue4 I definitely didn't expect it to get worse. Did you add the AAPL,GfxTile setting to the latest EFI? I don't believe it's there but should help. 

If that doesn't work I would definitely revert to the older version. Maybe also add AAPL,GfxTile to the old EFI and see if that helps at all.

Once I'm done resolving a few issues on the SP4 I'll take a look at these issues and bring over all the fixes.

**Comment by fjosue4** [comment]
I tried adding AAPL,GfxTile on the old EFI ([6.1.1](https://github.com/balopez83/Surface_Pro_3_Hackintosh/releases/tag/6.1.1)) and didn't fix it, I probably add it to the new one this afternoon just to try. 

Sure, no rush with this fix, I just opened the issue coz I didn't find anywhere else someone complaining about VSC on Hackintosh 😅 

I'll update once I try with the AAPL,GfxTile on 7.0.2.

Thanks for the follow-up.

**Comment by fjosue4** [comment]
Update using AAPL,GfxTile on v7.0.2 it didn't fix the bug, seems like VSC won't be compatible for now. I'll close the issue tomorrow if I don't find another thing doing some research. 

## First open
![Captura de Pantalla 2023-11-18 a la(s) 12 33 51](https://github.com/balopez83/Surface_Pro_3_Hackintosh/assets/85136931/b3543bd5-e568-41ed-ab5b-16c5e2ff7f2d)

## After moving the cursor on the program
![Captura de Pantalla 2023-11-18 a la(s) 12 34 34](https://github.com/balopez83/Surface_Pro_3_Hackintosh/assets/85136931/2af9d622-604a-4799-92ce-d0500f20b0f8)

**Comment by fjosue4** [comment]
Update! 

I got it working finally, the combination rn is having `AAPL,GfxTile` Data value `01000000` on EFI v7.0.2 and then running `open Visual\ Studio\ Code.app --args --disable-gpu` 

Thanks for the help @balopez83 !
![Captura de Pantalla 2023-11-18 a la(s) 19 04 36](https://github.com/balopez83/Surface_Pro_3_Hackintosh/assets/85136931/d522b1df-0bd8-4a3d-9a7a-dbafc765fb09)

**Comment by balopez83** [comment]
@fjosue4 apologies for not responding sooner. While I applaud your workaround its definitely not ideal since you are turning off graphics processing for those apps which will slow down processing. 

I am currently working on a solution as well as a lot of other fixes and cleanup which will be release in the next day or two. I believe I have resolved all graphics issues finally for all variations of the SP3. I have additionally tested VSC and have gotten it working with full graphics acceleration and no glitching at all. 

The next release will be changing the SMBIOS for the final time, so please be aware that you will need to sign out of any iServices before upgrading to the next release.

**Comment by balopez83** [comment]
@fjosue4 I believe that all issues have been resolved with graphics now. Please check out the latest release 8.0.0 that I just posted and your graphics should be fully working and you should be able to re-enable graphics acceleration in your apps.

**Comment by fjosue4** [comment]
Hey @balopez83 thanks for dropping the update so quickly! I'll try the new version this weekend and I'll let you know how it works on my device with the fixes.

**Comment by fjosue4** [comment]
@balopez83 I just installed the new version and the glitch is back as in the first comment of this issue. I've been using the i3i5i7.plist since I got the i5 version, do you recommend trying the i7 version?

**Comment by balopez83** [comment]
@fjosue4 so which version EFI are you using? There should only be a config-i3i5.plist and a config-i7.plist. I also am using the i5 version of the SP3 and have no glitches. Can you confirm you are using either the release 8.0.0 or 8.0.1? Also which macOS version are you using? I have currently tested on Monterey and Ventura and about to test on Sonoma.

**Comment by balopez83** [comment]
I would highly recommend updating to 8.0.1 if you are on Ventura or Sonoma or you will risk not being able to boot.

**Comment by fjosue4** [comment]
@balopez83 I'm using 8.0.0 with BigSur, I will try tonight/tomorrow the installing Sonoma version with 8.0.1

**Comment by balopez83** [comment]
Definitely don't use the i7 unless you have an i7 as you will experiencing graphics glitches when using Safari and possibly some other applications

**Comment by balopez83** [comment]
I will try and install Big Sur and see if I can duplicate your issues. As of now I have Chrome, Firefox, Safari, and VSC running and can't get it to glitch once. Everything is set to default and so is using graphics acceleration to its fullest. 

Only thing of note is that my SP3 which only has 4gb of ram runs slow with this many graphics accelerator intensive programs open. Firefox historically would cause issues and freeze but even that is running just fine now. 

Did you clean and reset your NVRAM? Maybe try that and see if that resolves the issue. It's possible some old boot-args may be stuck in your NVRAM causing some issues?

**Comment by fjosue4** [comment]
I'll try the NVRAM reset, my SP3 is the 8GB one, and I only installed VSC after the clean OS install on V8, after installing Sonoma with V8.0.1 and the NVRAM I'll let you know it gets if fixed.

**Comment by balopez83** [comment]
Weird. I will also try a clean Big Sur install and see if that improves things. I hope it's just a Big Sur issue cause I can't seem to duplicate the issue on Monterey and up.

**Comment by fjosue4** [comment]
I'm installing rn Ventura with v8.0.1 I'll update you in a few hours.

**Comment by balopez83** [comment]
@fjosue4 so I installed Big Sur and I was able to duplicate your issues. I am not sure why it is doing that on Big Sur but it does not seem to be causing those glitches in Monterey and newer so I would recommend using one of the newer versions of macOS. Since it seems to be working in the newer versions, I suspect it is an issue with something in Big Sur and likely would make it difficult to pinpoint a fix if one is even possible. 

Let me know if you have any issues after updating to Sonoma and installing OpenCore Legacy Patcher

**Comment by fjosue4** [comment]
Great, thanks for letting me know @balopez83 !
I was trying to install Ventura and Monterey but seems I did something wrong and it's no longer connecting correctly to the internet through mobile hotspot USB so can't download the OS from the recovery.

I reset NVRAM and swapped the disk, and now it's not even working with BigSur and an old EFI I had ready before. 

I'll try to fix it on the weekend together with a new OS version. But if you have a clue about the problem I'm having would be great. 

Using Safari in the recovery it says 'Not secure', so the connection is there but not properly working. 
On Install it says something like 'The server could not be contacted' instead of 'Internet is required' when the phone is not connected.

EDIT: It's not a date issue, I checked on the terminal, also set it manually and the server is not being contacted.

**Comment by balopez83** [comment]
@fjosue4 The date was my first thought so very curious that it's still not working after manually setting that. 

Are you using an Android or iPhone for the hotspot? I haven't ever really tried using a hotspot to download the recovery before but I can test when I have a moment and see if it works for me.

**Comment by fjosue4** [comment]
I'm using Android, and the weird part is I have installed all of them with the same setup, even with an old v6 EFI I tried last night, with no results. 
I have installed W10 just to check if the BIOS gets fixed or something, still failing.

In case you replicate it let me know, else I did break something on my machine for macOS.

**Comment by fjosue4** [comment]
I'm using Android, and the weird part is I have installed all the times with the same setup previously. Now even with an old v6 EFI I tried last night, with no results.
I have installed W10 just to check if the BIOS gets fixed or something, still failing.

@balopez83 In case you replicate it let me know, else I did break something on my machine for macOS, but on W10 all smoothly working.

**Comment by balopez83** [comment]
@fjosue4 You might have already tried it but see if resetting nvram after reverting to an old EFI makes it work again. I only have an iPhone that I can test on so it will be difficult for me to troubleshoot. 

I did make a change in the latest 8.x.x releases to the way kext handling is done which could have messed up the "horndis" kext that handles android tethering but that wouldn't have broken it for older releases unless something is stuck in nvram that broke it. Even the NVRAM thing seems far fetched though so I'll have to think on this one. Is there any chance that there could be a setting or issue with tethering on the phone? Maybe a phone restart might reset something with the phones dns? 

Just to clarify, did you also try it in a full macOS install and it also didn't work there?

**Comment by fjosue4** [comment]
@balopez83 Thanks for the follow-up. I'll try to reinstall it later today using an old EFI again and check with a secondary phone I got. But I'm almost sure the tethering is working perfectly. 

I always do the recovery + EFI on the USB process, I haven't tried with the full OS on the USB but pretty sure that should work since there seems to be a recovery issue with the Kext only on my device after the NVRAM clear.

**Comment by fjosue4** [comment]
Update @balopez83 

I was able to install Catalina (The only Full OS I have working for installation) using EFI v8.0.1 Surprisingly the tethering didn't work after installation this time. I was able to get Wi-Fi with the [additional drivers](https://github.com/balopez83/Surface_Pro_3_Hackintosh/blob/main/4-drivers.md) and using a USB dongle

I'll update to Ventura and see if the fix works (Catalina has glitch on VSC aswell)

![Screen Shot 2023-11-30 at 15 49 41](https://github.com/balopez83/Surface_Pro_3_Hackintosh/assets/85136931/760de197-834d-4ab1-98cc-81f8e23a9af3)

**Comment by balopez83** [comment]
@fjosue4 Do you have your screen set to the default resolution or did you adjust it so things were a little bigger and scaled properly? I am wondering if that is your issue. Surface screens in most generations get glitchy at their native resolution when not scaled and for some reason macOS does not scale it properly on the older OS's. I believe they are scaled correctly in Ventura and Sonoma though. Try adjusting your resolution to 1600x1066 and I suspect it will get rid of your glitching. 

On another note, try the attached configs. I have two that should work with your i5 Surface that might resolve the tethering issue assuming something went wrong with the most recent version. I re-enabled "Fuzzymatch" as well as moved the Horndis kext below the USBports.kext. The hope is that one or both of those changes would hopefully get your computer to recognize your phone as an internet source again. 
[i5-Configs.zip](https://github.com/balopez83/Surface_Pro_3_Hackintosh/files/13521560/i5-Configs.zip)

**Comment by balopez83** [comment]
Oh and the one that says low mem is designed for a 4gb ram SP3 as it frees up some of the RAM to go back to the OS and away from graphics speeding up the computer a bit. It can be used on the 8gb model as well if you find it speeds up your computer. The difference is 1,536mb on the 4gb config and 3,072mb for the standard config.

**Comment by fjosue4** [comment]
Yeah @balopez83 I'm using the default resolution, I'll try with the one you suggested but I'm still on Big Sur, I'l try using the Configs you shared for installing Ventura and let you know if the tethering works. Thanks!

**Comment by fjosue4** [comment]
You were right @balopez83 ! 
No issues on Big Sur with a lower resolution 🔥 
Thanks so much for the fix and the follow-up, I'm now able to use VSC without issues. 

I'll mark it as closed since the glitch is no longer there.
