### ISSUE TITLE
Mac OS Sequioa update?

### ISSUE THREAD

**Issue by b1t0y** [balopez83/Surface_Pro_3_Hackintosh#32]
Hi @balopez83  this not really an issue.  Just wanted to ask if you know if it is safe to update to Mac OS Sequoai with the last EFI with your 1.0.1  release?  Have you updated yours or should I stay with Sonoma still?   Just tempted to update to Sequoia on my SP3.  Thanks you for your work.

**Comment by balopez83** [comment]
@b1t0y  currently it's not safe. I need to update the entire EFI to enable support plus make sure that OCLP plays nice. I haven't had much time recently to test and so also am still on Sonoma.

If you can wait I would hold off till I can get a new update.

**Comment by b1t0y** [comment]
> @b1t0y currently it's not safe. I need to update the entire EFI to enable support plus make sure that OCLP plays nice. I haven't had much time recently to test and so also am still on Sonoma.
> 
> If you can wait I would hold off till I can get a new update.

Noted. Thanks for the reply. Will hold off and wait for your sequioa efi. Please let me know when you release it. Thanks again.

**Comment by balopez83** [comment]
@b1t0y Just published a pre-release version 8.4 in the releases page. I haven't had a chance to test it yet but it should work. Just make sure you download the latest version of Opencore Legacy Patcher before upgrading and make sure you update the EFI before upgrading as well. 
One more thing; nvmefixup.kext is not updated to work with Sequoia so depending on your model of SSD it could cause some issues with power management but I expect you will still be able to boot and use the computer.

**Comment by balopez83** [comment]
@b1t0y I have had a chance to test and it looks like all is working well. I have moved release 8.4.0 from pre-release to an actual release. 
Don't be surprised if Sequoia is a bit slow in the beginning even after running OCLP and its root patching. It should get better after indexing but the SP3 is pretty old and slow at this point. 

I am going to close this issue since Sequoia is now supported.

**Comment by b1t0y** [comment]
> @b1t0y I have had a chance to test and it looks like all is working well. I have moved release 8.4.0 from pre-release to an actual release. Don't be surprised if Sequoia is a bit slow in the beginning even after running OCLP and its root patching. It should get better after indexing but the SP3 is pretty old and slow at this point.
> 
> I am going to close this issue since Sequoia is now supported.
 
@balopez83 

Thank you so much for this and letting me know.  Appreciate it! I have upgraded too and all is working well with the updated EFI.  No issues so far.  BTW, my nvme is Samsung.  Should I not use the nvmefixup.kext?  Thanks again for making this possible! More power to you.

**Comment by balopez83** [comment]
@b1t0y I wouldn't worry about the kext for now unless you want to disable it. Currently it should fail to load as is without causing any issues. Once they release an updated version I will issue another release with the kext patched.
