### ISSUE TITLE
USB HID Devices do not work during setup

### ISSUE THREAD

**Issue by kymerea** [balopez83/Surface_Pro_3_Hackintosh#5]
Hi, as my Surface Pro 3 has a faulty touch screen and non-functional keyboard port I am forced to use a USB Keyboard and mouse, during the installer, I am unable to select the recovery as the keyboard and mouse do not work. It always boots into windows as is the default option in the recovery. What changes would have to be made such that USB keyboards and moues would work

**Comment by balopez83** [comment]
Hi @TheDingOfTheHud This is mentioned in the main instructions but the quick answer is that the Surface Pro 3 won't permit booting any other OS while Windows is installed until certain requirements are met: 

1. You must boot into your UEFI (Volume UP & Power Button) 
2. You must Turn OFF Secure boot in the UEFI. 
3. You must change the setting to have the Surface boot off USB first, then SSD
4. You can then boot to a properly set up Boot Disk that has my EFI loaded onto it. 
5. You should register the secure boot key (instructions linked on my main readme page)
6. You can then re-enable secure boot and it should still boot off the USB
7. Do not remove the USB until you have fully installed macOS and copied the EFI to your SSD

If you still have trouble booting macOS you will need to mount the EFI located on your SSD and rename your "EFI\Microsoft" folder to something else temporarily. (CAREFUL AS THIS WILL PREVENT YOUR ABILITY TO BOOT INTO WINDOWS UNTIL THIS RENAME IS REVERSED) 

I highly recommend creating a Linux live USB to aid in fixing any mistakes you might make to get your system booting again. Ubuntu is the easiest to use in this situation. 

Not sure why your USB keyboard isn't working but it should be however as mentioned above, the SP3 won't allow you to select an alternative OS for booting while Secure Boot is ON and with Windows installed.

**Comment by kymerea** [comment]
I did do all these instructions but I ended up using a different pair of mouse and keyboard which seemed to fix things. Thank you anyways.

**Comment by balopez83** [comment]
Glad it all ended up working for you. Not sure why the SP3 is so finicky but sometimes changing the hardware is all that's needed to fix things
