### ISSUE TITLE
Surface Pro 3 Monterey problem

### ISSUE THREAD

**Issue by MozzieMD** [balopez83/Surface_Pro_3_Hackintosh#8]
I installed Monterey on Surface Pro 3 , i5, 4gb, 128gb, nothing is working

- typecover
- trackpad
- volume keys
- wifi

I used the last version 4 of the efi release.
Can someone help me?

**Comment by balopez83** [comment]
Hi @MozzieMD , the built-in wifi card does not work with macOS and so you have to use an external wifi dongle. The instructions linked on the main readme links to the drivers for external usb wifi adapters as well as supported adapters.

Volume keys will only work from a warm boot after booting from Windows or Linux. This is a hardware issue and cannot be fixed unfortunately.

The type over and trackpad is a different story. I learned through a different closed issue that some of the typecover models do not work in macOS. In the previous closed issue the only resolution was to get one of the later models of the typecover. You can check the closed issue to see if your typecover model is the same as the problem one. The typecover is being driven by the voodooi2c kexts and so they don't seem to have support for the older models. You could try disabling the voodooi2chid custom kext though you will loose multi touch support for the trackpad and will lose touchscreen support.
Whatever you do, don't use the vanilla voodooi2chid kext as it will turn off the keyboard altogether.

I literally have the same model surface pro 3 so know everything works given the use of the latest versions of the typecover and a usb wifi adapter.

Hope this helps a little.

**Comment by MozzieMD** [comment]
Thank you for responding so fast!

**Comment by balopez83** [comment]
@MozzieMD were you able to get things working or are you still having issues? You may want to try the latest release and see if that resolves your issues if you are still having them.

**Comment by MozzieMD** [comment]
> @MozzieMD were you able to get things working or are you still having issues? You may want to try the latest release and see if that resolves your issues if you are still having them.

I just bought Macbook , so didn't try )

**Comment by balopez83** [comment]
> > @MozzieMD were you able to get things working or are you still having issues? You may want to try the latest release and see if that resolves your issues if you are still having them.
> 
> 
> 
> I just bought Macbook , so didn't try )

Ah ok, well if you decide you want to try later and need help feel free to reach out with issues. Except for some minor things, it's a fun little device to have macOS on.

**Comment by alessiotucci** [comment]
I am having the same issues with the keyboard, the blacklight turn on but it doesn't respond.

I want to say that this is my first hackintosh and I'm learning along the way.

I found our that some USB dongle are not supported ( I bought a USB 2-1 wifi and Bluetooth by tp link) and I had to look for drivers online.

I want to know if I bought new type cover or compatibles one is going do fix the issues... I don't mind have to plug in the USB dongle.

I have fixed the graphics glitch by change the display resolution, but I know there are other fix. 

I also want to dual boot with Tiny eleven.

**Comment by balopez83** [comment]
@alessiotucci 
> I am having the same issues with the keyboard, the blacklight turn on but it doesn't respond.
> 

This is common with some older model type covers. Ones designed for Surface Pro 4 and later generation type covers work fine from my experience. I personally use the Alcantera type covers and they work perfectly

> I want to say that this is my first hackintosh and I'm learning along the way.
> 
> I found our that some USB dongle are not supported ( I bought a USB 2-1 wifi and Bluetooth by tp link) and I had to look for drivers online.
> 
This list of compatible USB devices unfortunately isn't very long. You can check the list of compatible devices by following the link to Chris's software linked in my repo. As far as I know there are no 2 in 1 devices that currently work

> I want to know if I bought new type cover or compatibles one is going do fix the issues... I don't mind have to plug in the USB dongle.
> 
Yes; see response above
> I have fixed the graphics glitch by change the display resolution, but I know there are other fix. 
> 
The fixes vary by the hardware in your Surface but yes adjusting the resolution is going to improve it. I suspect you may still have occasional glitches and so may need to try my config fix though it does come with other drawbacks.
> I also want to dual boot with Tiny eleven. 
>

I have not tried tiny 11 yet but it should be doable. The trick is getting secure boot going before installing windows. Then you may also have to rename the "Microsoft" folder that windows creates in your EFI folder and then "blessing" that new folder in your OpenCore config. That will allow OpenCore to boot and then give you the option to select windows as the startup OS
